# Generated by Django 3.0.8 on 2020-08-02 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_color', models.CharField(max_length=50)),
                ('line_color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_time', models.PositiveIntegerField()),
                ('average_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_from', to='network.Station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_to', to='network.Station')),
                ('track_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Line')),
            ],
        ),
    ]
