# Generated by Django 3.0.8 on 2020-08-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='average_fare',
        ),
        migrations.RemoveField(
            model_name='track',
            name='average_time',
        ),
        migrations.AddField(
            model_name='line',
            name='average_speed',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='line',
            name='line_fare',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='distance',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
